# Generated by Django 2.2.5 on 2019-09-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='pwsd',
            new_name='password',
        ),
    ]
